-- users table
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test1@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test2@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test3@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test4@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test5@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test6@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test7@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test8@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test9@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test10@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test11@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test12@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test13@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test14@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test15@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test16@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test17@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test18@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test19@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test20@gmail.com', 1, 1);
INSERT INTO users (password, email, enabled, active_profile) VALUES ('$2a$10$3ZEsRHTWSPvpugmHUf/jZ.9wCWSJvHjJgl/PLQfougiimNIV/ihQu', 'test21@gmail.com', 1, 1);

-- profiles table
INSERT INTO profiles (profile_id, creation_date, username) VALUES (1, NOW(), 'Web2023');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (2, NOW(), 'PixelPioneer');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (3, NOW(), 'BlogEpicenter');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (4, NOW(), 'JaneBlogger23');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (5, NOW(), 'WriteLife2023');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (4, NOW(), 'KevinInkSpiller');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (5, NOW(), 'SamWebJourney');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (6, NOW(), 'TomBlogosphere');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (7, NOW(), 'BrianWebNarrator');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (8, NOW(), 'CreativeCaroline');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (9, NOW(), 'MarkWordCraft');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (10, NOW(), 'PennyProse');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (11, NOW(), 'JackJots');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (12, NOW(), 'OliviaOnlineDiary');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (13, NOW(), 'AlanArticles');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (14, NOW(), 'QuantumQuill');
INSERT INTO profiles (profile_id, creation_date, username) VALUES (15, NOW(), 'QuantumQuill');

-- posts table
INSERT INTO posts (creation_date, title, `description`, profile_id) VALUES (NOW(), 'Exploring Tuscany: A Food Lover\'s Journey', '##Introduction## \n The region of Tuscany in Italy is a treasure trove for any food lover. Known for its iconic landscapes, the warmth of its people, and a rich culinary tradition, it offers a captivating blend of history and gastronomy that is nothing short of inspiring. \n ##A Feast for the Senses## \n Upon arrival, you\'re immediately struck by the fragrance of fresh basil, rosemary, and thyme in the air. Local markets bustle with vendors offering a plethora of fresh produce, cured meats, and fragrant cheeses, each boasting of its own unique story. \n ##Culinary Adventures## \n The culinary adventures start in Florence, the region\'s capital, known for its Renaissance art and architecture. Among its narrow cobbled streets, countless trattorias invite you in for a taste of authentic Tuscan fare. Notable dishes include \'Bistecca alla Fiorentina\', a succulent T-bone steak, and \'Ribollita\', a hearty vegetable and bread soup. \n ##A Taste of the Countryside## \n Venturing into the countryside, you\'re welcomed by endless vineyards and olive groves that give Tuscany its renowned wines and olive oils. Visit the historic town of Montalcino, the birthplace of the famed Brunello di Montalcino wine, and enjoy a sip of this full-bodied red while gazing over the stunning Tuscan landscape. \n ##Learning the Tuscan Way## \n What\'s better than tasting delicious Tuscan dishes? Learning how to make them! Many Tuscan farms offer cooking classes where you can learn traditional cooking methods and recipes passed down through generations. It\'s a delightful experience that allows you to bring a piece of Tuscany back home. \n ##Conclusion## \n Tuscany\'s food is more than just a means to satiate hunger. It\'s a narrative of the region\'s history, a manifestation of the Tuscan way of life, and an art form that inspires joy and togetherness. As you travel through Tuscany, you don\'t just eat - you embark on a culinary journey that stirs your soul and tantalizes your taste buds. \n', 1);
INSERT INTO posts (creation_date, title, `description`, profile_id) VALUES (NOW(), 'Unveiling the Mysteries of the Cosmos: The James Webb Space Telescope', '##Introduction## \n The launch of the James Webb Space Telescope (JWST), the most powerful space telescope ever built, has opened a new chapter in our understanding of the universe. Referred to as the \'successor to Hubble\', the JWST promises to expand our understanding of the cosmos like never before. \n ##A Technological Marvel## \n The JWST, a result of collaboration between NASA, ESA, and CSA, stands as a testament to human ingenuity and the drive to explore the unknown. The telescope\'s 6.5-meter primary mirror, made of 18 hexagonal segments coated with ultra-thin gold, is nearly three times the size of Hubble\'s mirror, enabling it to collect more light and observe faint, distant objects. \n ##Decoding the Universe## \n The JWST\'s instruments are designed to observe in infrared, the part of the electromagnetic spectrum where many cosmic secrets lie hidden. It is expected to reveal the earliest galaxies formed after the Big Bang, study the atmospheres of exoplanets for possible signs of life, and uncover more about the mysterious dark matter and dark energy. \n ##The Journey So Far and What Lies Ahead## \n Following its successful launch, the JWST is now en route to its destination, the second Lagrange point (L2), located a million miles away from Earth. Once it unfolds its sunshield and aligns its mirror segments, the telescope will begin its mission, expected to last a decade or more. The scientific community awaits the first images and data with bated breath. \n ##Conclusion## \n The James Webb Space Telescope is a beacon of hope in our quest to comprehend the cosmos. As it gazes deep into the universe, we stand on the brink of new discoveries that could rewrite our understanding of our cosmic origins and our place in the universe. The journey has just begun. \n', 1);
INSERT INTO posts (creation_date, title, `description`, profile_id) VALUES (NOW(), 'The Magic of Moroccan Cuisine: Unlocking the Secrets of the Tagine', '##Introduction## \n Moroccan cuisine, with its intriguing blend of cultures and flavors, offers an enchanting culinary journey for food enthusiasts. The epitome of this gastronomic adventure is none other than the Tagine, a succulent slow-cooked stew named after the distinctive pot in which it is cooked. \n ##The Art of Tagine Cooking## \n Tagine cooking is a culinary art that has been passed down through generations. It involves slow-cooking meat, vegetables, and spices in a Tagine pot, a unique earthenware vessel with a conical lid that helps retain and circulate moisture and flavors. \n ##Recipe: Lamb Tagine with Prunes and Almonds## \n This delicious Moroccan Lamb Tagine recipe combines tender lamb with sweet prunes and crunchy almonds, creating a harmony of flavors and textures that\'s truly magical. Ingredients: \n 500g lamb, cut into chunks \n 2 onions, finely chopped \n 2 cloves of garlic, crushed \n 1 teaspoon ground cinnamon \n 1 teaspoon ground ginger \n 1/2 teaspoon saffron threads \n 2 tablespoons olive oil \n 250g prunes \n 100g blanched almonds \n 2 tablespoons honey \n Salt and pepper to taste \n Instructions: \n In a large bowl, marinate the lamb with the spices, garlic, salt, pepper, and olive oil. Let it sit for at least an hour. \n Place the tagine pot on a diffuser over medium heat. Add the marinated lamb and chopped onions. Cover and cook for about 1.5 hours. \n In a separate pan, toast the almonds until golden, then set aside. \n Add the prunes and honey to the tagine, cover, and continue to cook for another 30 minutes. \n Sprinkle the toasted almonds over the tagine just before serving. \n ##Conclusion## \n A tagine is more than just a dish; it\'s a celebration of Moroccan culture and a testament to the nation\'s love for vibrant, soulful food. So go ahead, try making a tagine at home and transport yourself to the bustling souks and fragrant kitchens of Morocco. Bon Appétit! \n', 1);
INSERT INTO posts (creation_date, title, `description`, profile_id) VALUES (NOW(), 'Journey Through History: The Allure of Rome\'s Colosseum', '##Introduction## \n The city of Rome is a historical treasure trove, its streets whispering tales of its imperial past. At the heart of this city stands a remarkable feat of ancient engineering and architectural grandeur - the Colosseum. \n ##Rome\'s Amphitheatrical Marvel## \n The Colosseum, or the Flavian Amphitheater, is a symbol of the grandeur of the Roman Empire. Built in 80 AD under Emperor Titus, it remains the largest amphitheater ever built, boasting a capacity of over 50,000 spectators. \n ##Echoes of the Past## \n Step into the Colosseum and you can almost hear the echoes of ancient Rome. This monumental structure was the stage for gladiatorial contests, public spectacles, and dramas based on Classical mythology. Despite the passage of nearly two millennia and the ravages of earthquakes and stone-robbers, the Colosseum still stands tall, a testament to the glory of Rome. \n ##The Colosseum Today## \n Today, the Colosseum is a major tourist attraction and an iconic symbol of Imperial Rome. It\'s an unmissable landmark for any visitor to the city, offering an incredible insight into Roman history, culture, and architecture. Night tours are particularly enchanting, as the amphitheater is beautifully illuminated, enhancing its majestic aura. \n ##Preserving the Colosseum## \n Efforts have been made to preserve this iconic structure for future generations to appreciate. The recent restoration, completed in 2016, cleaned and repaired a significant portion of the exterior, allowing the monument to regain some of its ancient splendor. \n ##Conclusion## \n A visit to the Colosseum is a journey through history, an opportunity to step back in time and marvel at the grandiosity of the Roman Empire. It\'s a reminder of our human capacity for greatness and an inspiration to preserve and honor our cultural heritage. \n', 1);
INSERT INTO posts (creation_date, title, `description`, profile_id) VALUES (NOW(), 'Dancing with the Northern Lights: A Night in Iceland', '##Introduction## \n Iceland, the land of fire and ice, holds a fascinating spectacle within its star-studded night skies - the Northern Lights. The aurora borealis, as it\'s scientifically known, is a mesmerizing sight, painting the sky with vibrant hues of green, pink, and purple. \n ##Chasing the Lights## \n The best time to witness this celestial ballet is during the cold, dark winters, particularly between September to April. The key to a good viewing is clear, dark skies away from city lights. \n ##A Night to Remember## \n Beneath the auroral glow, the landscape takes on an ethereal beauty, making it a magical experience. Remember to bundle up, as the nights can get chilly. But rest assured, it\'s a small price to pay for a front-row seat to one of nature\'s most spectacular shows. \n ##Conclusion## \n Seeing the Northern Lights is a bucket-list experience, a spectacle that reminds us of the earth\'s quiet yet profound magic. So, when in Iceland, look up! The night sky might just dance for you. \n', 1);
INSERT INTO posts (creation_date, title, `description`, profile_id) VALUES (NOW(), 'The Vibrant Palette of India\'s Holi Festival', '##Introduction## \n Holi, often referred to as the \'Festival of Colors\', is a boisterous celebration marking the arrival of spring in India. It\'s a time of joy, renewal, and vibrant colors. \n ##The Celebration## \n On Holi, people smear each other with colored powders, drench each other with water guns and balloons, and share sweets and laughter. The festivities transcend age, gender, and social status, encapsulating the spirit of unity and joy. \n ##Conclusion## \n Holi is more than just a festival; it\'s a celebration of life, love, and togetherness. It\'s a time when the air is filled with color and the sound of laughter, truly a sight to behold. \n', 1);
INSERT INTO posts (creation_date, title, `description`, profile_id) VALUES (NOW(), 'The Magnetic Pull of New York City\'s Central Park', '##Introduction## \n In the heart of the bustling metropolis of New York City lies a serene oasis - Central Park. This urban park, spanning over 843 acres, is a refuge for city dwellers and tourists alike. \n ##Central Park Highlights## \n From the verdant Sheep Meadow to the tranquil Bethesda Fountain, and the iconic Loeb Boathouse, Central Park offers myriad attractions that captivate the senses. \n ##Conclusion## \n Central Park is more than just a park; it\'s a testament to the city\'s architectural prowess and love for nature. It is indeed a breath of fresh air in the city that never sleeps. \n', 2);
INSERT INTO posts (creation_date, title, `description`, profile_id) VALUES (NOW(), 'Baking Bliss: The Joy of Homemade Bread', '##Introduction## \n The process of baking bread at home, with its comforting aroma and gratifying results, is a joyous culinary adventure. \n ##The Magic of Baking## \n From mixing the ingredients to kneading the dough and finally seeing it rise and brown in the oven, baking bread is a delightful experience. \n ##Conclusion## \n Baking bread at home not only offers a delectable treat but also a therapeutic and satisfying journey. So, go ahead and try your hand at baking. The results might just surprise you! \n', 3);
INSERT INTO posts (creation_date, title, `description`, profile_id) VALUES (NOW(), 'Unveiling the Deep: The Mystique of Scuba Diving', '##Introduction## \n Scuba diving is a gateway to a different world, a world of profound silence, vibrant colors, and diverse marine life. \n ##The Underwater Adventure## \n From exploring colorful coral reefs to encountering marine creatures, each dive is a unique adventure filled with excitement and awe. \n ##Conclusion## \n Scuba diving offers an escape from the terrestrial and a glimpse into the mesmerizing underwater world. It\'s an experience that resonates with the thrill of discovery and a deeper appreciation for our oceans. \n', 4);
INSERT INTO posts (creation_date, title, `description`, profile_id) VALUES (NOW(), 'The Art of Japanese Tea Ceremonies', '##Introduction## \n Japanese tea ceremonies, known as Chanoyu, are a time-honored tradition, steeped in ritual and mindfulness. \n ##The Ceremony## \n From the careful preparation of matcha to the deliberate and graceful serving, each step is a meditation in mindfulness. \n ##Conclusion## \n The tea ceremony is a beautiful embodiment of "Ichigo Ichie" - a Japanese idiom that translates to "one time, one meeting", reminding us to cherish every encounter. \n', 5);
INSERT INTO posts (creation_date, title, `description`, profile_id) VALUES (NOW(), 'Chasing Sunsets: The Charm of Santorini', '##Introduction## \n The Greek island of Santorini, with its blue-domed churches and sun-drenched cliffs, offers an exquisite display at sunset. \n ##The Sunset## \n As the sun dips into the Aegean Sea, the sky morphs into a kaleidoscope of colors, painting a breathtaking picture. \n ##Conclusion## \n Sunsets in Santorini are a spectacle of nature\'s beauty and a moment of serene reflection - a perfect end to a day in paradise. \n', 6);
INSERT INTO posts (creation_date, title, `description`, profile_id) VALUES (NOW(), 'Sustainable Living: Embracing Minimalism', '##Introduction## \n Minimalism, a lifestyle choice focusing on living with less, can lead to a sustainable, clutter-free, and fulfilling life. \n ##The Minimalist Lifestyle## \n By prioritizing needs over wants, minimalism helps us declutter, both physically and mentally. \n ##Conclusion## \n Adopting a minimalist lifestyle is a step towards sustainable living, fostering a sense of contentment an', 7);
INSERT INTO posts (creation_date, title, `description`, profile_id) VALUES (NOW(), 'Discovering Street Art: The Colorful Alleys of Berlin', '##Introduction## \n Berlin\'s vibrant street art scene is a visual narration of its history and cultural dynamism. \n ##The Street Art## \n From striking murals to thought-provoking graffiti, Berlin\'s street art transforms the urban landscape into an open-air gallery. \n ##Conclusion## \n Street art in Berlin is not merely an aesthetic endeavor but a medium of social commentary and creative expression, making the city a canvas of artistic liberation. \n', 8);
INSERT INTO posts (creation_date, title, `description`, profile_id) VALUES (NOW(), 'Exploring Vegan Cuisine: The Delightful Vegan Burger', '##Introduction## \n Veganism isn\'t just a diet; it\'s a lifestyle choice advocating for animal welfare and environmental sustainability. A delicious example of this is the vegan burger. \n ##The Vegan Burger## \n Made with plant-based ingredients, a vegan burger can be as juicy and flavorful as its meat counterpart. \n ##Conclusion## \n Embracing vegan cuisine doesn\'t mean compromising on taste. With a bit of creativity, a plant-based diet can offer a variety of flavorful and nutritious meals, such as the humble vegan burger. \n', 9);


-- comments table
INSERT INTO comments (creation_date, `description`, post_id, profile_id) VALUES (NOW(), 'This post brought back wonderful memories of my own trip to Tuscany. The food, the people, the landscapes - pure magic!', 1, 2);
INSERT INTO comments (creation_date, `description`, post_id, profile_id) VALUES (NOW(), 'The Northern Lights are truly a spectacle to behold! I\'m putting Iceland on my bucket list now.', 1, 7);
INSERT INTO comments (creation_date, `description`, post_id, profile_id) VALUES (NOW(), 'I\'ve always wanted to experience Holi in India. Your post beautifully captures the essence of this colorful festival.', 3, 6);
INSERT INTO comments (creation_date, `description`, post_id, profile_id) VALUES (NOW(), 'Central Park is indeed a haven in the midst of NYC\'s hustle and bustle. Lovely post!', 4, 8);
INSERT INTO comments (creation_date, `description`, post_id, profile_id) VALUES (NOW(), 'Baking bread at home has become a therapeutic activity for me during the lockdown. Thanks for this delightful post!', 1, 10);
INSERT INTO comments (creation_date, `description`, post_id, profile_id) VALUES (NOW(), 'Scuba diving seems like such an incredible experience. Your post has inspired me to give it a try!', 2, 4);
INSERT INTO comments (creation_date, `description`, post_id, profile_id) VALUES (NOW(), 'Chanoyu sounds like a beautiful tradition to experience. I\'d love to take part in a tea ceremony when I visit Japan.', 3, 6);
INSERT INTO comments (creation_date, `description`, post_id, profile_id) VALUES (NOW(), 'Sunsets in Santorini...sounds like a dream! Beautiful description.', 4, 7);
INSERT INTO comments (creation_date, `description`, post_id, profile_id) VALUES (NOW(), 'I\'ve been considering adopting minimalism for a while. This post gives me the push I needed. Thanks for sharing!', 5, 1);
INSERT INTO comments (creation_date, `description`, post_id, profile_id) VALUES (NOW(), 'Berlin\'s street art scene is definitely on my radar now. Can\'t wait to explore the city!', 5, 2);
INSERT INTO comments (creation_date, `description`, post_id, profile_id) VALUES (NOW(), 'Vegan cuisine can be so versatile and delicious. Your post on the vegan burger is a testament to that. Yum!', 5, 3);



-- followers table
INSERT INTO followers (creation_date, author_id, follower_id) VALUES (NOW(), 1, 2);
INSERT INTO followers (creation_date, author_id, follower_id) VALUES (NOW(), 1, 3);
INSERT INTO followers (creation_date, author_id, follower_id) VALUES (NOW(), 2, 1);
INSERT INTO followers (creation_date, author_id, follower_id) VALUES (NOW(), 3, 1);
INSERT INTO followers (creation_date, author_id, follower_id) VALUES (NOW(), 4, 1);

-- roles table
INSERT INTO roles (name) VALUES ('ROLE_USER');
INSERT INTO roles (name) VALUES ('ROLE_PROFILE_ACTIVE');
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');

-- users-roles table
INSERT INTO users_roles (role_id, user_id) VALUES (1, 1);
INSERT INTO users_roles (role_id, user_id) VALUES (2, 1);
INSERT INTO users_roles (role_id, user_id) VALUES (1, 2);
INSERT INTO users_roles (role_id, user_id) VALUES (1, 3);
--INSERT INTO users_roles (role_id, user_id) VALUES (2, 4);
INSERT INTO users_roles (role_id, user_id) VALUES (3, 5);

INSERT INTO users_roles (role_id, user_id) VALUES (1, 3);
INSERT INTO users_roles (role_id, user_id) VALUES (2, 3);

